name: SAST TEST
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  # Job 1: San on PR
  scan-pr:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication with Endor Labs
      issues: write # Required to automatically comment on PRs for new policy violations
      pull-requests: write # Required to automatically comment on PRs for new policy violations
    
    # Checkout repo 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

     # Setup Java 
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    # Maven Install
    - name: Install Dependencies
      run: mvn clean install 

    # Check PR and add PR comments
    - name: Endor Labs Scan Pull Request
      if: github.event_name == 'pull_request'
      uses: endorlabs/github-action@v1.8
      env:
        ENDOR_SCAN_SEMGREP_PROGRAM: opengrep
      with:
        namespace: 'kriti-learn' 
        scan_dependencies: false
        scan_sast: true
        github_token: ${{ secrets.GITHUB_TOKEN }} # Required for PR comments on new policy violations
        pr: true
        pr_baseline:  ${{ inputs.defaultBranch }}
        enable_pr_comments: true
  
  # Job 2: scan-main
  scan-main:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      repository-projects: read
      pull-requests: read
      contents: read
      security-events: write
    
    name: endorctl-scan
    steps:
    - uses: actions/checkout@v3
    - name: 'Endor Labs Scan Push to main'
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      uses: endorlabs/github-action@main
      env:
        ENDOR_SCAN_SEMGREP_PROGRAM: opengrep
      with:
        namespace: 'kriti-learn'
        scan_dependencies: true
        scan_secrets: true
        scan_sast: true
        pr: false
        scan_summary_output_type: 'table'
        sarif_file: 'findings.sarif'
        additional_args: --as-default-branch 
    
 
